### ISSUE TITLE
[Need help]播放网络视频失败求正确使用姿势

### ISSUE THREAD

**Issue by aerokwok** [CaiJingLong/flutter_ijkplayer#147]
使用网络视频报错,还是说需要什么初始化吗？？？
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.6 18G95, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)
```

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'setNetworkDataSource' was called on null.
Receiver: null
Tried calling: setNetworkDataSource("https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4")
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
#1      _MediaPlayerPageState.initVideoPlayerWithUrl 
package:ireadabc_student/…/player_page/media_player_page.dart:36
<asynchronous suspension>
#2      _MediaPlayerPageState.playNumChange 
package:ireadabc_student/…/player_page/media_player_page.dart:41
#3      _MediaPlayerPageState.build.<anonymous closure> 
package:ireadabc_student/…/player_page/media_player_page.dart:104
#4      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:654
#5      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:729
#6      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
#7      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:365
#8      TapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:275
#9      PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:455
#10     PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:75
#11     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:102
#12     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:218
#13     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
#14     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
#15     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
#16     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
#17     _rootRunUnary  (dart:async/zone.dart:1136:13)
#18     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
#19     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
#20     _invoke1  (dart:ui/hooks.dart:263:10)
#21     _dispatchPointerDataPacket  (dart:ui/hooks.dart:172:5)
```
```
class MediaPlayerPage extends StatefulWidget {
  @override
  _MediaPlayerPageState createState() => _MediaPlayerPageState();
}

class _MediaPlayerPageState extends State<MediaPlayerPage> {
  IjkMediaController controller = IjkMediaController();

  List mediaList = [];

  int playIndex = 0;

  @override
  void initState() {
    super.initState();
    getMediaListData(1);
  }

  @override
  void dispose() {
    // TODO: implement dispose
    controller.dispose();
    super.dispose();
  }

  void initVideoPlayerWithUrl(String url) async {
    await controller.setNetworkDataSource(
        'https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4',
        autoPlay: true);
  }

  void playNumChange(int index) {
    initVideoPlayerWithUrl('url');
  }

  void getMediaListData(int themeId) async {
    getVideoPlayerList(themeId).then((_) {
      mediaList = _['data']['rows'];
      setState(() {});
      print('===================$_');
    });
  }

  Widget buildIjkPlayer() {
    return Container(
      // height: 400, // 这里随意

      child: IjkPlayer(
        mediaController: controller,
        statusWidgetBuilder: _buildStatusWidget,
      ),
    );
  }

  Widget _buildStatusWidget(
    BuildContext context,
    IjkMediaController controller,
    IjkStatus status,
  ) {
    if (status == IjkStatus.noDatasource) {
      return Center(
        child: Text(
          "no data",
          style: TextStyle(color: Colors.white),
        ),
      );
    }
    // you can custom your self status widget
    return IjkStatusWidget.buildStatusWidget(context, controller, status);
  }
```

**Comment by CaiJingLong** [comment]
具体的还是看不出来, 可能需要进一步的信息
比如提供一个可运行可复现的 example
包含运行步骤

**Comment by CaiJingLong** [comment]
不过可能和 #135  是同一个问题

**Comment by aerokwok** [comment]
我这边现在setnetsource以后什么反应都没有。await也能过，就是没声音然后黑屏

**Comment by aerokwok** [comment]
FFP_MSG_ERROR: 0
是什么问题咧

**Comment by CaiJingLong** [comment]
关于播放不了的问题, 一般原因都比较复杂, 这个东西云debug比较难

**Comment by aerokwok** [comment]
好吧，我看看源码去

**Comment by CaiJingLong** [comment]
另外说一下..  这个example中的网站似乎挂了 www.sample-videos.com  的主页似乎都上不去了
所以下面所有的资源都是播不了的
因为我写 example 的时候 这个地址是可用的, 我后续会把所有的示例地址更换一下

**Comment by aerokwok** [comment]
是的，我发现了，换了我自己的地址后可以用了




在2019年10月23日 17:28，Caijinglong 写道：

另外说一下.. 这个example中的网站似乎挂了 www.sample-videos.com �的主页似乎都上不去了
所以下面所有的资源都是播不了的
因为我写 example 的时候 这个地址是可用的, 我后续会把所有的示例地址更换一下

**Comment by CaiJingLong** [comment]
然后 今天这 sample-videos 又可以访问了
