### ISSUE TITLE
[Bug] 打正式包后闪退

### ISSUE THREAD

**Issue by qjb6049941** [CaiJingLong/flutter_ijkplayer#265]
### 下面是报错信息
```
[ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/xxxxxxxxxxxx-A1v69y3xJjDEic_4ShMpdA==/lib/arm64/libijksdl.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$a.a(Unknown Source:0)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.b(Unknown Source:18)
        at i.a.a.e.a(Unknown Source:11)
        at d.a.b.a.j$a.a(Unknown Source:17)
        at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:330)
        at android.os.Looper.loop(Looper.java:169)
        at android.app.ActivityThread.main(ActivityThread.java:7042)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:868)
2020-09-08 17:20:19.349 16159-16159/? A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env). 
    
    
    --------- beginning of crash
2020-09-08 17:20:19.537 16255-16255/? A/DEBUG: Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env). 
    '
2020-09-08 17:20:19.538 16255-16255/? A/DEBUG:     #01 pc 00000000002bcc80  /data/app/xxxxxxxxxxxxxx-A1v69y3xJjDEic_4ShMpdA==/lib/arm64/libflutter.so (offset 0x29d000)
```
android 打包关闭混淆后可以正常使用

**Comment by qjb6049941** [comment]
环境
```
[✓] Flutter (Channel stable, 1.20.0, on Mac OS X 10.15.6 19G2021, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2020.2.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)
```
