### ISSUE TITLE
打包debug一切都正常,但是打包release启动闪退.

### ISSUE THREAD

**Issue by hu70258tao** [CaiJingLong/flutter_ijkplayer#271]
通过抓取日志,发现一个error
[ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/irricontro.yikongce-Vqu_DVzvl2Uk692SDpDe1A==/lib/arm64/libijksdl.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$a.a(Unknown Source:0)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.b(Unknown Source:18)
        at g.a.a.e.a(Unknown Source:11)
        at d.a.c.a.j$a.a(Unknown Source:17)
        at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by hu70258tao** [comment]
通过解析包.debug和so比release范反而少一个,
![image](https://user-images.githubusercontent.com/20218008/99161197-b3961800-272a-11eb-9c5b-32709ff0fd40.png)
![image](https://user-images.githubusercontent.com/20218008/99161201-bb55bc80-272a-11eb-8f8d-2cb09ac9aadc.png)

**Comment by Ronny-dev** [comment]
加混淆配置即可
