### ISSUE TITLE
[Bug] pod install报错

### ISSUE THREAD

**Issue by liuhong1happy** [CaiJingLong/flutter_ijkplayer#291]
[!] Error installing FlutterIJK
[!] /usr/bin/curl -f -L -o /var/folders/ys/0hm8kwrs6fx5q5hv78yw08840000gn/T/d20210603-31553-111bwfx/file.txz https://bintray.com/api/ui/download/caijinglong/cocoapod/0.1.1/IJKMediaFramework.tar.xz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

**Comment by lifeng-Lee** [comment]
啥时候 更新呀，更新下吧，卡你这 动不了了

**Comment by lifeng-Lee** [comment]
-> Installing FlutterIJK (0.1.1)
     > Http download
       $ /usr/bin/curl -f -L -o /var/folders/hb/7g5lzqq14ws1h7jjcj518kwm0000gn/T/d20210610-46831-1dyp3kk/file.txz
       https://bintray.com/api/ui/download/caijinglong/cocoapod/0.1.1/IJKMediaFramework.tar.xz --create-dirs --netrc-optional
       --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

    [!] Error installing FlutterIJK
    [!] /usr/bin/curl -f -L -o /var/folders/hb/7g5lzqq14ws1h7jjcj518kwm0000gn/T/d20210610-46831-1dyp3kk/file.txz
    https://bintray.com/api/ui/download/caijinglong/cocoapod/0.1.1/IJKMediaFramework.tar.xz --create-dirs --netrc-optional
    --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

**Comment by lifeng-Lee** [comment]
-> Installing FlutterIJK (0.1.1)
     > Http download
       $ /usr/bin/curl -f -L -o /var/folders/hb/7g5lzqq14ws1h7jjcj518kwm0000gn/T/d20210616-83838-1il5i4m/file.txz
       https://bintray.com/api/ui/download/caijinglong/cocoapod/0.1.1/IJKMediaFramework.tar.xz --create-dirs --netrc-optional --retry 2 -A
       'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

    [!] Error installing FlutterIJK
    [!] /usr/bin/curl -f -L -o /var/folders/hb/7g5lzqq14ws1h7jjcj518kwm0000gn/T/d20210616-83838-1il5i4m/file.txz
    https://bintray.com/api/ui/download/caijinglong/cocoapod/0.1.1/IJKMediaFramework.tar.xz --create-dirs --netrc-optional --retry 2 -A
    'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--
  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  0     0    0     0    0     0
  0      0 --:--:--  0:00:03 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
    curl: (22) The requested URL returned error: 404 Not Found

**Comment by lifeng-Lee** [comment]
这是 什么问题呀

**Comment by lifeng-Lee** [comment]
作者倒是 说句话呀

**Comment by IOS-Chao** [comment]
我也遇到同样的问题 
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader.rb:142:in `rescue in execute_command'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader.rb:139:in `execute_command'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-downloader-1.4.0/lib/cocoapods-downloader/base.rb:166:in `block in executable'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-downloader-1.4.0/lib/cocoapods-downloader/http.rb:22:in `download_file'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-downloader-1.4.0/lib/cocoapods-downloader/remote_file.rb:25:in `download!'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-downloader-1.4.0/lib/cocoapods-downloader/base.rb:82:in `block in download'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader.rb:157:in `block in ui_action'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader.rb:156:in `ui_action'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-downloader-1.4.0/lib/cocoapods-downloader/base.rb:80:in `download'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader.rb:108:in `download_source'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader.rb:75:in `download_request'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:171:in `download'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader.rb:42:in `download'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/pod_source_installer.rb:118:in `download_source'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:561:in `install_source_of_pod'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:512:in `block (2 levels) in install_pod_sources'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:511:in `block in install_pod_sources'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:494:in `each'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:494:in `install_pod_sources'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:253:in `block in download_dependencies'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:252:in `download_dependencies'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:161:in `install!'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/mac/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/mac/.rvm/gems/ruby-2.5.1@global/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/mac/.rvm/rubies/ruby-2.5.1/bin/pod:23:in `load'
/Users/mac/.rvm/rubies/ruby-2.5.1/bin/pod:23:in `<main>'

**Comment by freecodemans** [comment]
怎么解决的啊，折磨了我好久，有人能回复一下吗

**Comment by freecodemans** [comment]
> 这是 什么问题呀

解决了吗？能说说吗

**Comment by freecodemans** [comment]
帮忙看看
 
> Http download
   $ /usr/bin/curl -f -L -o /var/folders/6v/h6f4f2h567ggwqkpqq8tpsy00000gn/T/d20210816-99920-1ve9mew/file.txz
   https://bintray.com/api/ui/download/caijinglong/cocoapod/0.1.1/IJKMediaFramework.tar.xz --create-dirs --netrc-optional
   --retry 2 -A 'CocoaPods/1.9.3 cocoapods-downloader/1.4.0'
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
   curl: (22) The requested URL returned error: 403 Forbidden

[!] Error installing FlutterIJK
[!] /usr/bin/curl -f -L -o /var/folders/6v/h6f4f2h567ggwqkpqq8tpsy00000gn/T/d20210816-99920-1ve9mew/file.txz https://bintray.com/api/ui/download/caijinglong/cocoapod/0.1.1/IJKMediaFramework.tar.xz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.9.3 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden

**Comment by IOS-Chao** [comment]
这个估计过期了库不存在了 下载不了，我换了个框架&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月16日(星期一) 中午11:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CaiJingLong/flutter_ijkplayer] [Bug] pod install报错 (#291)





 
帮忙看看
  
Http download
 $ /usr/bin/curl -f -L -o /var/folders/6v/h6f4f2h567ggwqkpqq8tpsy00000gn/T/d20210816-99920-1ve9mew/file.txz
 https://bintray.com/api/ui/download/caijinglong/cocoapod/0.1.1/IJKMediaFramework.tar.xz --create-dirs --netrc-optional
 --retry 2 -A 'CocoaPods/1.9.3 cocoapods-downloader/1.4.0'
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
 Dload  Upload   Total   Spent    Left  Speed
 0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
 curl: (22) The requested URL returned error: 403 Forbidden
  
[!] Error installing FlutterIJK
 [!] /usr/bin/curl -f -L -o /var/folders/6v/h6f4f2h567ggwqkpqq8tpsy00000gn/T/d20210816-99920-1ve9mew/file.txz https://bintray.com/api/ui/download/caijinglong/cocoapod/0.1.1/IJKMediaFramework.tar.xz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.9.3 cocoapods-downloader/1.4.0'
 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
 Dload  Upload   Total   Spent    Left  Speed
 0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
 curl: (22) The requested URL returned error: 403 Forbidden
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuzhou721** [comment]
修改一下flutter_ijkplayer里的ios文件夹flutter_ijkplayer.podspec里的FlutterIJK版本依赖 我在cocoa里查了下 最新的是1.2.0  改了就恢复了
